name: brother_printer
description: BRLMPrinterKit Brother's printer SDK
version: 0.1.0
homepage: https://github.com/jonathantribouharet/flutter_brother_printer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: any
  equatable: ">=2.0.0 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: co.eivo.brother_printer
        pluginClass: BrotherPrinterPlugin
      ios:
        pluginClass: BrotherPrinterPlugin
